text  = $"Konstants {KONSTANTS_VERSION}, {KONSTANTS_DATE}\n";
text += "\n";
if (K_RUNNING_FROM_IDE) text += "K_RUNNING_FROM_IDE = true\n";
if (K_WINDOWS) text += "K_WINDOWS = true\n";
if (K_MACOS) text += "K_MACOS = true\n";
if (K_LINUX) text += "K_LINUX = true\n";
if (K_IOS) text += "K_IOS = true\n";
if (K_TVOS) text += "K_TVOS = true\n";
if (K_XBOX_SERIES_X) text += "K_XBOX_SERIES_X = true\n";
if (K_XBOX_SERIES_S) text += "K_XBOX_SERIES_S = true\n";
if (K_XBOX_SERIES_ANY) text += "K_XBOX_SERIES_ANY = true\n";
if (K_PS4) text += "K_PS4 = true\n";
if (K_PS5) text += "K_PS5 = true\n";
if (K_SWITCH) text += "K_SWITCH = true\n";
if (K_SWITCH_2) text += "K_SWITCH_2 = true\n";
if (K_GXGAMES) text += "K_GXGAMES = true\n";
if (K_HTML5) text += "K_HTML5 = true\n";
if (K_DESKTOP) text += "K_DESKTOP = true\n";
if (K_MOBILE) text += "K_MOBILE = true\n";
if (K_APPLE) text += "K_APPLE = true\n";
if (K_XBOX) text += "K_XBOX = true\n";
if (K_PSX) text += "K_PSX = true\n";
if (K_PSX) text += "K_PSX = true\n";
if (K_SWITCH_X) text += "K_SWITCH_X = true\n";
if (K_OPENGL) text += "K_OPENGL = true\n";
if (K_WEB) text += "K_WEB = true\n";
if (K_STEAMWORKS) text += "K_STEAMWORKS = true\n";
if (K_GAMECENTER) text += "K_GAMECENTER = true\n";
if (K_PLAY_SERVICES) text += "K_PLAY_SERVICES = true\n";
if (K_WINDOWS_GDK) text += "K_WINDOWS_GDK = true\n";
if (K_XBOX_GDK) text += "K_XBOX_GDK = true\n";
if (K_STEAMWORKS_PRESENT) text += "K_STEAMWORKS_PRESENT = true\n";
if (K_PLAY_SERVICES_PRESENT) text += "K_PLAY_SERVICES_PRESENT = true\n";
if (K_PS3) text += "K_PS3 = true\n";
if (K_XBOX_ONE) text += "K_XBOX_ONE = true\n";
text += "\n";
text += "Debug:\n";
text += $"os_type = {os_type}\n";
text += $"os_browser = {os_browser}\n";